SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

DROP DATABASE IF EXISTS theqa_form;

CREATE DATABASE theqa_form;

USE theqa_form;

-- this is the first table
CREATE TABLE `employee_specific` (
    `user_id` int(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`user_id`),
    `dateOfdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    -- box 1
    `user_name` varchar(225) NOT NULL,
    UNIQUE (`user_name`),
    `user_email` varchar(225) NOT NULL,
    UNIQUE (`user_email`),
    `job_name` varchar(225) NOT NULL,
    `enlistment` varchar(225) NOT NULL,
    `nationality` varchar(225) NOT NULL,
    `religion` varchar(225) NOT NULL,
    `marital_status` varchar(225) NOT NULL,
    `dateOFbirth` varchar(225) NOT NULL,
    `placeOFbirth` varchar(225) NOT NULL,
    `address` varchar(225) NOT NULL,
    `address_street` varchar(225) NOT NULL,
    `numberOFphpne` varchar(225) NOT NULL,
    `frontOFcard` varchar(225) NOT NULL,
    `backOFcard` varchar(225) NOT NULL,
    `photoOFuser` varchar(225) NOT NULL,
    -- box 2
    `sideOFstudy` varchar(225) NOT NULL,
    `specialization` varchar(225) NOT NULL,
    `graduation_year` varchar(225) NOT NULL,
    `educational_qualification` varchar(225) NOT NULL,
    -- box 3
    `course_name` varchar(225) NOT NULL,
    `course_location` varchar(225) NOT NULL,
    `course_duration` varchar(225) NOT NULL,
    `typeOFcertificate` varchar(225) NOT NULL,
    `photoOFcertificate` varchar(225) NOT NULL,
    -- box 4
    `job_name_1` varchar(225) NOT NULL,
    `job_duration_1` varchar(225) NOT NULL,
    `pointOFstart_1` varchar(225) NOT NULL,
    `pointOFend_1` varchar(225) NOT NULL,
    `salary_1` varchar(225) NOT NULL,
    `reasonFORleaving_1` varchar(225) NOT NULL,
    `do_you_work_1` varchar(225) NOT NULL,
    `attached_1` varchar(225) NOT NULL,
    `responsibilities_1` varchar(225) NOT NULL,
    -- box 5
    `job_name_2` varchar(225) NULL,
    `job_duration_2` varchar(225) NULL,
    `pointOFstart_2` varchar(225) NULL,
    `pointOFend_2` varchar(225) NULL,
    `salary_2` varchar(225) NULL,
    `reasonFORleaving_2` varchar(225) NULL,
    `attached_2` varchar(225) NULL,
    `responsibilities_2` varchar(225) NULL,
    -- box 6
    `job_name_3` varchar(225) NULL,
    `job_duration_3` varchar(225) NULL,
    `pointOFstart_3` varchar(225) NULL,
    `pointOFend_3` varchar(225) NULL,
    `salary_3` varchar(225) NULL,
    `reasonFORleaving_3` varchar(225) NULL,
    `attached_3` varchar(225) NULL,
    `responsibilities_3` varchar(225) NULL,
    -- box 7
    `job_name_4` varchar(225) NULL,
    `job_duration_4` varchar(225) NULL,
    `pointOFstart_4` varchar(225) NULL,
    `pointOFend_4` varchar(225) NULL,
    `salary_4` varchar(225) NULL,
    `reasonFORleaving_4` varchar(225) NULL,
    `attached_4` varchar(225) NULL,
    `responsibilities_4` varchar(225) NULL,
    -- box 8
    `person_name_1` varchar(225) NOT NULL,
    `person_employer_1` varchar(225) NOT NULL,
    `person_address_1` varchar(225) NOT NULL,
    `person_phone_1` varchar(225) NOT NULL,
    -- box 9
    `person_name_2` varchar(225) NOT NULL,
    `person_employer_2` varchar(225) NOT NULL,
    `person_address_2` varchar(225) NOT NULL,
    `person_phone_2` varchar(225) NOT NULL,
    -- box 10
    `person_name_3` varchar(225) NOT NULL,
    `person_employer_3` varchar(225) NOT NULL,
    `person_address_3` varchar(225) NOT NULL,
    `person_phone_3` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- this is the second table
CREATE TABLE `employee_postpone` (
    `user_id` int(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`user_id`),
    `dateOfdate` DATETIME NOT NULL, 
    -- box 1
    `user_name` varchar(225) NOT NULL,
    `user_email` varchar(225) NOT NULL,
    `job_name` varchar(225) NOT NULL,
    `enlistment` varchar(225) NOT NULL,
    `nationality` varchar(225) NOT NULL,
    `religion` varchar(225) NOT NULL,
    `marital_status` varchar(225) NOT NULL,
    `dateOFbirth` varchar(225) NOT NULL,
    `placeOFbirth` varchar(225) NOT NULL,
    `address` varchar(225) NOT NULL,
    `address_street` varchar(225) NOT NULL,
    `numberOFphpne` varchar(225) NOT NULL,
    `frontOFcard` varchar(225) NOT NULL,
    `backOFcard` varchar(225) NOT NULL,
    `photoOFuser` varchar(225) NOT NULL,
    -- box 2
    `sideOFstudy` varchar(225) NOT NULL,
    `specialization` varchar(225) NOT NULL,
    `graduation_year` varchar(225) NOT NULL,
    `educational_qualification` varchar(225) NOT NULL,
    -- box 3
    `course_name` varchar(225) NOT NULL,
    `course_location` varchar(225) NOT NULL,
    `course_duration` varchar(225) NOT NULL,
    `typeOFcertificate` varchar(225) NOT NULL,
    `photoOFcertificate` varchar(225) NOT NULL,
    -- box 4
    `job_name_1` varchar(225) NOT NULL,
    `job_duration_1` varchar(225) NOT NULL,
    `pointOFstart_1` varchar(225) NOT NULL,
    `pointOFend_1` varchar(225) NOT NULL,
    `salary_1` varchar(225) NOT NULL,
    `reasonFORleaving_1` varchar(225) NOT NULL,
    `do_you_work_1` varchar(225) NOT NULL,
    `attached_1` varchar(225) NOT NULL,
    `responsibilities_1` varchar(225) NOT NULL,
    -- box 5
    `job_name_2` varchar(225) NULL,
    `job_duration_2` varchar(225) NULL,
    `pointOFstart_2` varchar(225) NULL,
    `pointOFend_2` varchar(225) NULL,
    `salary_2` varchar(225) NULL,
    `reasonFORleaving_2` varchar(225) NULL,
    `attached_2` varchar(225) NULL,
    `responsibilities_2` varchar(225) NULL,
    -- box 6
    `job_name_3` varchar(225) NULL,
    `job_duration_3` varchar(225) NULL,
    `pointOFstart_3` varchar(225) NULL,
    `pointOFend_3` varchar(225) NULL,
    `salary_3` varchar(225) NULL,
    `reasonFORleaving_3` varchar(225) NULL,
    `attached_3` varchar(225) NULL,
    `responsibilities_3` varchar(225) NULL,
    -- box 7
    `job_name_4` varchar(225) NULL,
    `job_duration_4` varchar(225) NULL,
    `pointOFstart_4` varchar(225) NULL,
    `pointOFend_4` varchar(225) NULL,
    `salary_4` varchar(225) NULL,
    `reasonFORleaving_4` varchar(225) NULL,
    `attached_4` varchar(225) NULL,
    `responsibilities_4` varchar(225) NULL,
    -- box 8
    `person_name_1` varchar(225) NOT NULL,
    `person_employer_1` varchar(225) NOT NULL,
    `person_address_1` varchar(225) NOT NULL,
    `person_phone_1` varchar(225) NOT NULL,
    -- box 9
    `person_name_2` varchar(225) NOT NULL,
    `person_employer_2` varchar(225) NOT NULL,
    `person_address_2` varchar(225) NOT NULL,
    `person_phone_2` varchar(225) NOT NULL,
    -- box 10
    `person_name_3` varchar(225) NOT NULL,
    `person_employer_3` varchar(225) NOT NULL,
    `person_address_3` varchar(225) NOT NULL,
    `person_phone_3` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- this is the third table
CREATE TABLE `employee_appointed` (
    `user_id` int(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`user_id`),
    `dateOfdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    -- box 1
    `user_name` varchar(225) NOT NULL,
    UNIQUE (`user_name`),
    `user_email` varchar(225) NOT NULL,
    UNIQUE (`user_email`),
    `job_name` varchar(225) NOT NULL,
    `enlistment` varchar(225) NOT NULL,
    `nationality` varchar(225) NOT NULL,
    `religion` varchar(225) NOT NULL,
    `marital_status` varchar(225) NOT NULL,
    `dateOFbirth` varchar(225) NOT NULL,
    `placeOFbirth` varchar(225) NOT NULL,
    `address` varchar(225) NOT NULL,
    `address_street` varchar(225) NOT NULL,
    `numberOFphpne` varchar(225) NOT NULL,
    `frontOFcard` varchar(225) NOT NULL,
    `backOFcard` varchar(225) NOT NULL,
    `photoOFuser` varchar(225) NOT NULL,
    -- box 2
    `sideOFstudy` varchar(225) NOT NULL,
    `specialization` varchar(225) NOT NULL,
    `graduation_year` varchar(225) NOT NULL,
    `educational_qualification` varchar(225) NOT NULL,
    -- box 3
    `course_name` varchar(225) NOT NULL,
    `course_location` varchar(225) NOT NULL,
    `course_duration` varchar(225) NOT NULL,
    `typeOFcertificate` varchar(225) NOT NULL,
    `photoOFcertificate` varchar(225) NOT NULL,
    -- box 4
    `job_name_1` varchar(225) NOT NULL,
    `job_duration_1` varchar(225) NOT NULL,
    `pointOFstart_1` varchar(225) NOT NULL,
    `pointOFend_1` varchar(225) NOT NULL,
    `salary_1` varchar(225) NOT NULL,
    `reasonFORleaving_1` varchar(225) NOT NULL,
    `do_you_work_1` varchar(225) NOT NULL,
    `attached_1` varchar(225) NOT NULL,
    `responsibilities_1` varchar(225) NOT NULL,
    -- box 5
    `job_name_2` varchar(225) NULL,
    `job_duration_2` varchar(225) NULL,
    `pointOFstart_2` varchar(225) NULL,
    `pointOFend_2` varchar(225) NULL,
    `salary_2` varchar(225) NULL,
    `reasonFORleaving_2` varchar(225) NULL,
    `attached_2` varchar(225) NULL,
    `responsibilities_2` varchar(225) NULL,
    -- box 6
    `job_name_3` varchar(225) NULL,
    `job_duration_3` varchar(225) NULL,
    `pointOFstart_3` varchar(225) NULL,
    `pointOFend_3` varchar(225) NULL,
    `salary_3` varchar(225) NULL,
    `reasonFORleaving_3` varchar(225) NULL,
    `attached_3` varchar(225) NULL,
    `responsibilities_3` varchar(225) NULL,
    -- box 7
    `job_name_4` varchar(225) NULL,
    `job_duration_4` varchar(225) NULL,
    `pointOFstart_4` varchar(225) NULL,
    `pointOFend_4` varchar(225) NULL,
    `salary_4` varchar(225) NULL,
    `reasonFORleaving_4` varchar(225) NULL,
    `attached_4` varchar(225) NULL,
    `responsibilities_4` varchar(225) NULL,
    -- box 8
    `person_name_1` varchar(225) NOT NULL,
    `person_employer_1` varchar(225) NOT NULL,
    `person_address_1` varchar(225) NOT NULL,
    `person_phone_1` varchar(225) NOT NULL,
    -- box 9
    `person_name_2` varchar(225) NOT NULL,
    `person_employer_2` varchar(225) NOT NULL,
    `person_address_2` varchar(225) NOT NULL,
    `person_phone_2` varchar(225) NOT NULL,
    -- box 10
    `person_name_3` varchar(225) NOT NULL,
    `person_employer_3` varchar(225) NOT NULL,
    `person_address_3` varchar(225) NOT NULL,
    `person_phone_3` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- this is the Fourth table
CREATE TABLE `delete_specific` (
    `user_id` int(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`user_id`),
    `dateOfdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    -- box 1
    `user_name` varchar(225) NOT NULL,
    UNIQUE (`user_name`),
    `user_email` varchar(225) NOT NULL,
    UNIQUE (`user_email`),
    `job_name` varchar(225) NOT NULL,
    `enlistment` varchar(225) NOT NULL,
    `nationality` varchar(225) NOT NULL,
    `religion` varchar(225) NOT NULL,
    `marital_status` varchar(225) NOT NULL,
    `dateOFbirth` varchar(225) NOT NULL,
    `placeOFbirth` varchar(225) NOT NULL,
    `address` varchar(225) NOT NULL,
    `address_street` varchar(225) NOT NULL,
    `numberOFphpne` varchar(225) NOT NULL,
    `frontOFcard` varchar(225) NOT NULL,
    `backOFcard` varchar(225) NOT NULL,
    `photoOFuser` varchar(225) NOT NULL,
    -- box 2
    `sideOFstudy` varchar(225) NOT NULL,
    `specialization` varchar(225) NOT NULL,
    `graduation_year` varchar(225) NOT NULL,
    `educational_qualification` varchar(225) NOT NULL,
    -- box 3
    `course_name` varchar(225) NOT NULL,
    `course_location` varchar(225) NOT NULL,
    `course_duration` varchar(225) NOT NULL,
    `typeOFcertificate` varchar(225) NOT NULL,
    `photoOFcertificate` varchar(225) NOT NULL,
    -- box 4
    `job_name_1` varchar(225) NOT NULL,
    `job_duration_1` varchar(225) NOT NULL,
    `pointOFstart_1` varchar(225) NOT NULL,
    `pointOFend_1` varchar(225) NOT NULL,
    `salary_1` varchar(225) NOT NULL,
    `reasonFORleaving_1` varchar(225) NOT NULL,
    `do_you_work_1` varchar(225) NOT NULL,
    `attached_1` varchar(225) NOT NULL,
    `responsibilities_1` varchar(225) NOT NULL,
    -- box 5
    `job_name_2` varchar(225) NULL,
    `job_duration_2` varchar(225) NULL,
    `pointOFstart_2` varchar(225) NULL,
    `pointOFend_2` varchar(225) NULL,
    `salary_2` varchar(225) NULL,
    `reasonFORleaving_2` varchar(225) NULL,
    `attached_2` varchar(225) NULL,
    `responsibilities_2` varchar(225) NULL,
    -- box 6
    `job_name_3` varchar(225) NULL,
    `job_duration_3` varchar(225) NULL,
    `pointOFstart_3` varchar(225) NULL,
    `pointOFend_3` varchar(225) NULL,
    `salary_3` varchar(225) NULL,
    `reasonFORleaving_3` varchar(225) NULL,
    `attached_3` varchar(225) NULL,
    `responsibilities_3` varchar(225) NULL,
    -- box 7
    `job_name_4` varchar(225) NULL,
    `job_duration_4` varchar(225) NULL,
    `pointOFstart_4` varchar(225) NULL,
    `pointOFend_4` varchar(225) NULL,
    `salary_4` varchar(225) NULL,
    `reasonFORleaving_4` varchar(225) NULL,
    `attached_4` varchar(225) NULL,
    `responsibilities_4` varchar(225) NULL,
    -- box 8
    `person_name_1` varchar(225) NOT NULL,
    `person_employer_1` varchar(225) NOT NULL,
    `person_address_1` varchar(225) NOT NULL,
    `person_phone_1` varchar(225) NOT NULL,
    -- box 9
    `person_name_2` varchar(225) NOT NULL,
    `person_employer_2` varchar(225) NOT NULL,
    `person_address_2` varchar(225) NOT NULL,
    `person_phone_2` varchar(225) NOT NULL,
    -- box 10
    `person_name_3` varchar(225) NOT NULL,
    `person_employer_3` varchar(225) NOT NULL,
    `person_address_3` varchar(225) NOT NULL,
    `person_phone_3` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- this is the Fifth table
CREATE TABLE `delete_postpone` (
    `user_id` int(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`user_id`),
    `dateOfdate` DATETIME NOT NULL, 
    -- box 1
    `user_name` varchar(225) NOT NULL,
    `user_email` varchar(225) NOT NULL,
    `job_name` varchar(225) NOT NULL,
    `enlistment` varchar(225) NOT NULL,
    `nationality` varchar(225) NOT NULL,
    `religion` varchar(225) NOT NULL,
    `marital_status` varchar(225) NOT NULL,
    `dateOFbirth` varchar(225) NOT NULL,
    `placeOFbirth` varchar(225) NOT NULL,
    `address` varchar(225) NOT NULL,
    `address_street` varchar(225) NOT NULL,
    `numberOFphpne` varchar(225) NOT NULL,
    `frontOFcard` varchar(225) NOT NULL,
    `backOFcard` varchar(225) NOT NULL,
    `photoOFuser` varchar(225) NOT NULL,
    -- box 2
    `sideOFstudy` varchar(225) NOT NULL,
    `specialization` varchar(225) NOT NULL,
    `graduation_year` varchar(225) NOT NULL,
    `educational_qualification` varchar(225) NOT NULL,
    -- box 3
    `course_name` varchar(225) NOT NULL,
    `course_location` varchar(225) NOT NULL,
    `course_duration` varchar(225) NOT NULL,
    `typeOFcertificate` varchar(225) NOT NULL,
    `photoOFcertificate` varchar(225) NOT NULL,
    -- box 4
    `job_name_1` varchar(225) NOT NULL,
    `job_duration_1` varchar(225) NOT NULL,
    `pointOFstart_1` varchar(225) NOT NULL,
    `pointOFend_1` varchar(225) NOT NULL,
    `salary_1` varchar(225) NOT NULL,
    `reasonFORleaving_1` varchar(225) NOT NULL,
    `do_you_work_1` varchar(225) NOT NULL,
    `attached_1` varchar(225) NOT NULL,
    `responsibilities_1` varchar(225) NOT NULL,
    -- box 5
    `job_name_2` varchar(225) NULL,
    `job_duration_2` varchar(225) NULL,
    `pointOFstart_2` varchar(225) NULL,
    `pointOFend_2` varchar(225) NULL,
    `salary_2` varchar(225) NULL,
    `reasonFORleaving_2` varchar(225) NULL,
    `attached_2` varchar(225) NULL,
    `responsibilities_2` varchar(225) NULL,
    -- box 6
    `job_name_3` varchar(225) NULL,
    `job_duration_3` varchar(225) NULL,
    `pointOFstart_3` varchar(225) NULL,
    `pointOFend_3` varchar(225) NULL,
    `salary_3` varchar(225) NULL,
    `reasonFORleaving_3` varchar(225) NULL,
    `attached_3` varchar(225) NULL,
    `responsibilities_3` varchar(225) NULL,
    -- box 7
    `job_name_4` varchar(225) NULL,
    `job_duration_4` varchar(225) NULL,
    `pointOFstart_4` varchar(225) NULL,
    `pointOFend_4` varchar(225) NULL,
    `salary_4` varchar(225) NULL,
    `reasonFORleaving_4` varchar(225) NULL,
    `attached_4` varchar(225) NULL,
    `responsibilities_4` varchar(225) NULL,
    -- box 8
    `person_name_1` varchar(225) NOT NULL,
    `person_employer_1` varchar(225) NOT NULL,
    `person_address_1` varchar(225) NOT NULL,
    `person_phone_1` varchar(225) NOT NULL,
    -- box 9
    `person_name_2` varchar(225) NOT NULL,
    `person_employer_2` varchar(225) NOT NULL,
    `person_address_2` varchar(225) NOT NULL,
    `person_phone_2` varchar(225) NOT NULL,
    -- box 10
    `person_name_3` varchar(225) NOT NULL,
    `person_employer_3` varchar(225) NOT NULL,
    `person_address_3` varchar(225) NOT NULL,
    `person_phone_3` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- this is the Sixth table
CREATE TABLE `delete_appointed` (
    `user_id` int(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`user_id`),
    `dateOfdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    -- box 1
    `user_name` varchar(225) NOT NULL,
    UNIQUE (`user_name`),
    `user_email` varchar(225) NOT NULL,
    UNIQUE (`user_email`),
    `job_name` varchar(225) NOT NULL,
    `enlistment` varchar(225) NOT NULL,
    `nationality` varchar(225) NOT NULL,
    `religion` varchar(225) NOT NULL,
    `marital_status` varchar(225) NOT NULL,
    `dateOFbirth` varchar(225) NOT NULL,
    `placeOFbirth` varchar(225) NOT NULL,
    `address` varchar(225) NOT NULL,
    `address_street` varchar(225) NOT NULL,
    `numberOFphpne` varchar(225) NOT NULL,
    `frontOFcard` varchar(225) NOT NULL,
    `backOFcard` varchar(225) NOT NULL,
    `photoOFuser` varchar(225) NOT NULL,
    -- box 2
    `sideOFstudy` varchar(225) NOT NULL,
    `specialization` varchar(225) NOT NULL,
    `graduation_year` varchar(225) NOT NULL,
    `educational_qualification` varchar(225) NOT NULL,
    -- box 3
    `course_name` varchar(225) NOT NULL,
    `course_location` varchar(225) NOT NULL,
    `course_duration` varchar(225) NOT NULL,
    `typeOFcertificate` varchar(225) NOT NULL,
    `photoOFcertificate` varchar(225) NOT NULL,
    -- box 4
    `job_name_1` varchar(225) NOT NULL,
    `job_duration_1` varchar(225) NOT NULL,
    `pointOFstart_1` varchar(225) NOT NULL,
    `pointOFend_1` varchar(225) NOT NULL,
    `salary_1` varchar(225) NOT NULL,
    `reasonFORleaving_1` varchar(225) NOT NULL,
    `do_you_work_1` varchar(225) NOT NULL,
    `attached_1` varchar(225) NOT NULL,
    `responsibilities_1` varchar(225) NOT NULL,
    -- box 5
    `job_name_2` varchar(225) NULL,
    `job_duration_2` varchar(225) NULL,
    `pointOFstart_2` varchar(225) NULL,
    `pointOFend_2` varchar(225) NULL,
    `salary_2` varchar(225) NULL,
    `reasonFORleaving_2` varchar(225) NULL,
    `attached_2` varchar(225) NULL,
    `responsibilities_2` varchar(225) NULL,
    -- box 6
    `job_name_3` varchar(225) NULL,
    `job_duration_3` varchar(225) NULL,
    `pointOFstart_3` varchar(225) NULL,
    `pointOFend_3` varchar(225) NULL,
    `salary_3` varchar(225) NULL,
    `reasonFORleaving_3` varchar(225) NULL,
    `attached_3` varchar(225) NULL,
    `responsibilities_3` varchar(225) NULL,
    -- box 7
    `job_name_4` varchar(225) NULL,
    `job_duration_4` varchar(225) NULL,
    `pointOFstart_4` varchar(225) NULL,
    `pointOFend_4` varchar(225) NULL,
    `salary_4` varchar(225) NULL,
    `reasonFORleaving_4` varchar(225) NULL,
    `attached_4` varchar(225) NULL,
    `responsibilities_4` varchar(225) NULL,
    -- box 8
    `person_name_1` varchar(225) NOT NULL,
    `person_employer_1` varchar(225) NOT NULL,
    `person_address_1` varchar(225) NOT NULL,
    `person_phone_1` varchar(225) NOT NULL,
    -- box 9
    `person_name_2` varchar(225) NOT NULL,
    `person_employer_2` varchar(225) NOT NULL,
    `person_address_2` varchar(225) NOT NULL,
    `person_phone_2` varchar(225) NOT NULL,
    -- box 10
    `person_name_3` varchar(225) NOT NULL,
    `person_employer_3` varchar(225) NOT NULL,
    `person_address_3` varchar(225) NOT NULL,
    `person_phone_3` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- this is the Seventh table
CREATE TABLE `users` (
    `user_id` int(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`user_id`),
    `user_name` varchar(225) NOT NULL,
    `user_email` varchar(225) NOT NULL,
    UNIQUE (`user_email`),
    `user_password` varchar(225) NOT NULL,
    `ability` varchar(25) NOT NULL,
    `job` varchar(100) NOT NULL,
    `active` varchar(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;